### ISSUE TITLE
Not generating alot of results (perhaps a discord issue)

### ISSUE THREAD

**Issue by whatyoumeanbih** [apolo1337/BadgesScraper#18]
Hey dude,

first of all great job this is sick.

I just wanted to ask.. on a server with 1200 members, I tried to parse and it worked, however it only generated me 17 users. I deleted the results.txt, and then tried using a different channel id but it still only gave me the same 17 users (which appeared to be admins of the server).

Is this an issue with discord in general or is it an issue with how i'm using your script?

**Comment by ottersec2015** [comment]
Im working on this

**Comment by ottersec2015** [comment]
Fixed

**Comment by fireheadman** [comment]
curious of the fix... I have only been able to get listings of bots on a discord server and not the complete user list

**Comment by kieren1** [comment]
This is still an issue it would seem
